# Generated by Django 4.2.6 on 2023-10-23 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('regiao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Prefiro não dizer', 'Prefiro não dizer'), ('Outro', 'Outro')], max_length=100)),
                ('corouraca', models.CharField(choices=[('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Indegena', 'Indegena'), ('Pardo', 'Pardo'), ('Preto', 'Preto')], max_length=100)),
                ('disciplina', models.ManyToManyField(related_name='teacher', to='school_app.schoolsubject')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Prefiro não dizer', 'Prefiro não dizer'), ('Outro', 'Outro')], max_length=100)),
                ('corouraca', models.CharField(choices=[('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Indegena', 'Indegena'), ('Pardo', 'Pardo'), ('Preto', 'Preto')], max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.school')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.class')),
            ],
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='professor',
            field=models.ManyToManyField(related_name='subjects', to='school_app.teacher'),
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='student',
            field=models.ManyToManyField(related_name='subjects', to='school_app.student'),
        ),
        migrations.CreateModel(
            name='SchoolBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('licao', models.FileField(upload_to='licoes/')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='professor',
            field=models.ManyToManyField(related_name='turma', to='school_app.teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1° Bimestre', '1° Bimestre'), ('2° Bimestre', '2° Bimestre'), ('3° Bimestre', '3° Bimestre'), ('4° Bimestre', '4° Bimestre')], max_length=200)),
                ('ano_letivo', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
